import type { Metadata } from 'next'
import '@ant-design/v5-patch-for-react-19';
import "@/app/globals.css"
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { ConfigProvider, App } from 'antd'; // Import App
import "./antd.css"

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`} style={{ margin: 0 }}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              components: {
                Slider: {
                  railBg: "rgba(233, 233, 233, 1)",
                  railHoverBg: "rgba(227, 227, 227, 1)"
                },
              },
            }}
          >
            <App>
              {children}
            </App>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  )
}
