import type { Metadata } from "next";
import "@ant-design/v5-patch-for-react-19";
import "@/app/globals.css";
import Providers from "@/providers/provider";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  console.log("layout rendering")
  return (
    <html lang="en">
      <body className="antialiased" style={{ margin: 0 }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
