services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - lumiroom-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    restart: unless-stopped
    networks:
      - lumiroom-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: lumiroom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - lumiroom-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./backend/lumiroom
      dockerfile: Dockerfile
    container_name: lumiroom-backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      # ollama:
        # condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lumiroom
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    restart: unless-stopped
    networks:
      - lumiroom-network

  # nginx:
  #   image: nginx:latest
  #   container_name: lumiroom-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - /etc/letsencrypt/live/lumiroom.duckdns.org:/etc/letsencrypt/live/lumiroom.duckdns.org:ro
  #     - /etc/letsencrypt/archive/lumiroom.duckdns.org:/etc/letsencrypt/archive/lumiroom.duckdns.org:ro

  #   depends_on:
  #     - backend
  #   restart: unless-stopped
  #   networks:
  #     - lumiroom-network
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama-gpu
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     # Mount your host model directory directly where Ollama expects it
  #     - D:/ollama/models:/root/.ollama/models
  #   environment:
  #     - OLLAMA_HOST=0.0.0.0
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - OLLAMA_KEEP_ALIVE=10m
  #     - OLLAMA_MAX_LOADED_MODELS=1
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]
  #   restart: unless-stopped
  #   networks:
  #     - lumiroom-network

volumes:
  redis_data:
  pgdata:
  ollama_data:
    driver: local  # Define the local volume to persist Ollama data

networks:
  lumiroom-network:
    driver: bridge
