# render.yaml
services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/lumiroom/Dockerfile
    plan: standard
    instanceCount: 1
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://postgres:5432/lumiroom
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: postgres
      - key: SPRING_REDIS_HOST
        value: redis
      - key: SPRING_REDIS_PORT
        value: 6379
      - key: SPRING_RABBITMQ_HOST
        value: rabbitmq
      - key: SPRING_RABBITMQ_PORT
        value: 5672
      - key: SPRING_RABBITMQ_USERNAME
        value: guest
      - key: SPRING_RABBITMQ_PASSWORD
        value: guest

  - type: redis
    name: redis
    plan: free

  - type: postgres
    name: postgres
    plan: starter
    databaseName: lumiroom
    user: postgres
    password: postgres

  - type: worker
    name: rabbitmq
    env: docker
    dockerfilePath: ./rabbitmq/Dockerfile
    plan: starter
    instanceCount: 1
