"use client";

import React, { useState } from "react";
// import { useRouter } from "next/navigation";
import {
  Form,
  Input,
  Button,
  Typography,
  Alert,
  Row,
  Col,
  Card,
  Tabs,
} from "antd";
import {
  LeftOutlined,
  RightOutlined,
  LoginOutlined,
  UserOutlined,
} from "@ant-design/icons";
import { LumiAvatar } from "@/components/LumiAvatar";
import { signIn, signOut } from "@/utils/user";
import { verifyOtp, requestOtp } from "@/utils/user";
import { SupabaseUser, SignInArgs } from "@/types/datatypes";
import globalStore from "@/store";
// import { useGlobalStore } from "@/store";

const { Title } = Typography;

export default function AuthPage() {
  // const router = useRouter();

  const [user, setUser] = useState<SupabaseUser | null>(null);
  const [formType, setFormType] = useState<"login" | "register">("login");
  const [step, setStep] = useState<"register" | "verify">("register");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [email, setEmail] = useState("");
  const [username, setUsername] = useState("");
  const [avatarId, setAvatarId] = useState("1");

  // // this will not be updated in the UI, but is used when verify OTP
  // const [password, setPassword] = useState("");


  const [loginForm] = Form.useForm();
  const [registerForm] = Form.useForm();
  const [verifyForm] = Form.useForm();

  const handleAvatarNavigation = (dir: "prev" | "next") => {
    let id = parseInt(avatarId);
    id = dir === "prev" ? (id <= 1 ? 32 : id - 1) : (id >= 32 ? 1 : id + 1);
    setAvatarId(id.toString());
    registerForm.setFieldsValue({ avatar_id: id.toString() });
  };

  // when register, we just send the OTP
  // the user will eventually be created in verifyOtp
  // so we don't need to create a user here
  const onRegister = async (values: Omit<SupabaseUser, "id" | "created_at" | "onboarding_complete"> & { password: string }) => {
    setLoading(true);
    setError(null);

    const { username, email, avatar_id } = values;

    try {
      setUsername(username);
      setEmail(email);
      setAvatarId(avatar_id.toString());
      // setPassword(values.password);

      await requestOtp(email, username, values.password);
      setStep("verify");
    } catch (err) {
      if (err instanceof Error) setError(err.message || "Registration failed.");
      else setError("An unexpected error occurred.");
    } finally {
      setLoading(false);
    }
  };

  // this verifies the OTP and creates the user
  // but we enforce password to be set
  const onVerify = async (values: { token: string }) => {
    setLoading(true);
    setError(null);
    try {
      await verifyOtp(values.token, email)
      await globalStore.setItem<SupabaseUser>('lumiroom-user', {
        id: "", // id is generated by supabase, cannot preset
        email,
        username,
        avatar_id: parseInt(avatarId),
        onboarding_complete: true,
      })
      window.location.href = "/"

      // router.push("/");
    } catch (err) {
      if (err instanceof Error) setError(err.message || "Verification failed.");
      else setError("An unexpected error occurred.");
    } finally {
      setLoading(false);
    }
  };

  const onLogin = async (values: SignInArgs) => {
    setLoading(true);
    setError(null);
    try {
      // Determine if username or email provided
      let emailToUse = values.email;
      if (!emailToUse && values.username) {
        // If only username given, fetch email by username or just use username as login
        emailToUse = values.username; // Assuming signIn supports username or email here
      }

      if (!emailToUse) {
        throw new Error("Either username or email must be provided");
      }

      const resUser = await signIn({ identifier: emailToUse, password: values.password });
      if (resUser) {
        setUser(resUser);
        await globalStore.setItem<SupabaseUser>('lumiroom-user', resUser)
        // useGlobalStore.getState().setUser(resUser)
        // router.push("/");
        window.location.href = "/"
      } else {
        setError("Invalid username/email or password");
      }
    } catch (err) {
      if (err instanceof Error) setError(err.message || "Login failed.");
      else setError("An unexpected error occurred.");
    } finally {
      setLoading(false);
    }
  };

  const onLogout = async () => {
    setLoading(true);
    try {
      await signOut();
      setUser(null);
      await globalStore.removeItem('lumiroom-user')
      window.location.href = "/auth"
      // router.push("/auth");
    } catch (err) {
      if (err instanceof Error) setError(err.message || "Logout failed.");
      else setError("An unexpected error occurred.");
    } finally {
      setLoading(false);
    }
  };

  const LoginForm = () => (
    <Form form={loginForm} layout="vertical" onFinish={onLogin} autoComplete="off">
      <Form.Item
        label="Username or Email"
        name="username"
        rules={[{ required: true, message: "Please enter username or email" }]}
      >
        <Input />
      </Form.Item>
      <Form.Item
        label="Password"
        name="password"
        rules={[{ required: true, message: "Please enter your password" }]}
      >
        <Input.Password />
      </Form.Item>
      {error && (
        <Alert
          type="error"
          message={error}
          showIcon
          style={{ marginBottom: 16 }}
        />
      )}
      <Button type="primary" htmlType="submit" loading={loading} block>
        Login
      </Button>
    </Form>
  );

  const RegisterForm = () => (
    <Form
      form={registerForm}
      layout="vertical"
      onFinish={onRegister}
      initialValues={{ avatar_id: avatarId }}
      autoComplete="off"
    >
      <Form.Item
        label="Username"
        name="username"
        rules={[
          { required: true, message: "Please enter a username" },
          { min: 3, message: "Username must be at least 3 characters" },
          { max: 20, message: "Username must be at most 20 characters" },
        ]}
      >
        <Input />
      </Form.Item>

      <Form.Item
        label="Email"
        name="email"
        rules={[
          { required: true, message: "Please enter an email" },
          { type: "email", message: "Please enter a valid email" },
        ]}
      >
        <Input />
      </Form.Item>

      <Form.Item
        label="Password"
        name="password"
        rules={[
          { required: true, message: "Please enter a password" },
          { min: 3, message: "Password must be at least 3 characters" },
        ]}
      >
        <Input.Password />
      </Form.Item>

      <Form.Item label="Avatar">
        <Row justify="center" align="middle" gutter={16}>
          <Col>
            <Button icon={<LeftOutlined />} onClick={() => handleAvatarNavigation("prev")} />
          </Col>
          <Col>
            <div
              key={avatarId}
              className="transition-opacity duration-300 ease-in-out opacity-100"
            >
              <LumiAvatar avatarId={avatarId} />
            </div>
          </Col>
          <Col>
            <Button icon={<RightOutlined />} onClick={() => handleAvatarNavigation("next")} />
          </Col>
        </Row>
      </Form.Item>

      <Form.Item
        label="Avatar ID"
        name="avatar_id"
        rules={[
          { required: true, message: "Please enter an avatar ID" },
          {
            pattern: /^\d+$/,
            message: "Avatar ID must be a number",
          },
          {
            validator: (_, value) =>
              value >= 1 && value <= 32
                ? Promise.resolve()
                : Promise.reject(new Error("Avatar ID must be between 1 and 32")),
          },
        ]}
      >
        <Input
          type="number"
          min={1}
          max={32}
          onChange={(e) => {
            const val = e.target.value;
            setAvatarId(val);
            registerForm.setFieldsValue({ avatar_id: val });
          }}
        />
      </Form.Item>

      {error && (
        <Alert
          type="error"
          message={error}
          showIcon
          style={{ marginBottom: 16 }}
        />
      )}
      <Button type="primary" htmlType="submit" loading={loading} block>
        Register & Send OTP
      </Button>
    </Form>
  );

const VerifyOtpForm = () => (
  <Form
    form={verifyForm}
    layout="vertical"
    onFinish={onVerify}
    autoComplete="off"
  >
    <Form.Item
      label="Enter the confirmation code from your email"
      name="token"
      rules={[{ required: true, message: "Please enter the verification code" }]}
    >
      <Input.OTP
        length={6}
        separator={<span>/</span>}
        onChange={(val) => verifyForm.setFieldsValue({ token: val })}
        autoFocus
      />
    </Form.Item>

    {error && (
      <Alert
        type="error"
        message={error}
        showIcon
        style={{ marginBottom: 16 }}
      />
    )}

    <Button type="primary" htmlType="submit" loading={loading} block>
      Verify Email
    </Button>
  </Form>
);


  if (user) {
    return (
      <Card style={{ maxWidth: 500, margin: "40px auto", textAlign: "center" }}>
        <Title level={3}>Welcome, {user.username}</Title>
        <div
          key={avatarId}
          className="transition-opacity duration-300 ease-in-out opacity-100"
          style={{ marginBottom: 16 }}
        >
          <LumiAvatar avatarId={avatarId} />
        </div>
        <Button
          type="primary"
          danger
          onClick={onLogout}
          loading={loading}
          style={{ marginTop: 24 }}
          block
        >
          Logout
        </Button>
      </Card>
    );
  }

  const items = [
    {
      key: "login",
      label: (
        <>
          <LoginOutlined />
          Login
        </>
      ),
      children: <LoginForm />,
    },
    {
      key: "register",
      label: (
        <>
          <UserOutlined />
          Register
        </>
      ),
      children: step === "register" ? <RegisterForm /> : <VerifyOtpForm />,
    },
  ];

  return (
    <div style={{ maxWidth: 500, margin: "60px auto", padding: 24 }}>
      <Card>
        <Tabs
          activeKey={formType}
          onChange={(key) => {
            setFormType(key as "login" | "register");
            setStep("register");
            setError(null);
            loginForm.resetFields();
            registerForm.resetFields();
            verifyForm.resetFields();
          }}
          items={items}
        />
      </Card>
    </div>
  );
}
