# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: lumiroom
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/lumiroom
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: user
      password: 123
  profiles:
    active:
    - sender
    - receiver
    - auth
  jackson:
    property-naming-strategy: SNAKE_CASE
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl