import type { Metadata } from 'next'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import '@ant-design/v5-patch-for-react-19';
import "@/app/globals.css"
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { StreamVideoProvider } from '@/providers/StreamProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ margin: 0 }}>
          <StreamVideoProvider>
            <AntdRegistry>{children}</AntdRegistry>
          </StreamVideoProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}